default_platform(:ios)

xcversion(version: "~> 13")

platform :ios do
  desc "Perform unit tests"
  lane :test do
  run_tests(
    scheme: "CV",
    device: "iPhone 13 Pro Max",
    code_coverage: true,
    derived_data_path: "build"
  )
  end
end
