default_platform(:ios)

xcversion(version: "~> 13")

platform :ios do
  desc "Perform unit tests"
  lane :test do
  run_tests(
    scheme: "CV",
    code_coverage: true,
    derived_data_path: "build"
  )
  end
end

platform :ios do
  desc "Submit tests report to codecov"
  lane :codecov do
  codecov_reporter(
    token: "$CODECOV_TOKEN"
  )
  end
end
